[WIP] Feat: custom liveness
Polymarket/uma-ctf-adapter pull request #58
Opened 2023-01-25 23:39 UTC by JonathanAmenechi

## Overview

## Description

## Testing instructions

## Types of changes

- [ ] Refactor/enhancement 
- [ ] Bug fix/behavior correction 
- [ ] New feature 
- [ ] Breaking change 
- [ ] Other, additional 

## Notes

## Status

- [ ] Prefix PR title with `WIP` if necessary (changes not yet made).
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation/changelog as needed.
- [ ] Verify all tests run correctly in CI and pass.
- [ ] Ready for review/merge.

2023-05-25 19:32 UTC, L-Kov commented on src/UmaCtfAdapter.sol
> +    /// @param liveness      - UMA liveness period. If 0, the default liveness period is used.
seconds?

2023-05-25 19:34 UTC, L-Kov approved these changes

2023-05-25 19:40 UTC, JonathanAmenechi commented on src/UmaCtfAdapter.sol
> +    /// @param liveness      - UMA liveness period. If 0, the default liveness period is used.
Will add to the natspec 👍

2023-05-25 19:57 UTC, mshrieve requested changes

2023-05-25 19:57 UTC, mshrieve commented on src/test/UmaCtfAdapter.t.sol
can we add an assert here to check that the defaultLiveness was used?

2023-05-25 19:57 UTC, mshrieve commented on src/test/UmaCtfAdapter.t.sol
>          assertFalse(data.resolved);
can we add an assertion that the defaultLiveness was used?

2023-05-27 00:37 UTC, mshrieve approved these changes
looking good

2023-05-27 04:58 UTC, L-Kov approved these changes

2023-05-31 16:44 UTC, merged